# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'ReactiveDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveDemo
  pod "ReactiveSwift"
  pod "ReactiveCocoa"

  target 'ReactiveDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveDemoUITests' do
    # Pods for testing
  end

end
